#file: noinspection SpellCheckingInspection

services:
  ### Workspace ############################################
  workspace:
    build:
      context: ./workspace
      args:
        # Core configuration
        - PHP_VERSION
        - TZ
        - APP_USER
        - APP_UID
        - APP_GID
        - DEPENDENCY_PHP_EXTENSIONS
        # Node.js
        - NODE_VERSION
    restart: on-failure:3
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "${BROWSERSYNC_HOST_PORT}:3000"
      - "${BROWSERSYNC_UI_HOST_PORT}:3001"
      - "${VITE_PORT}:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ
      # Container user configuration
      - APP_USER
      - APP_UID
      - APP_GID
      # Cron configuration
      - CRONTAB_DIR=/etc/crontab.d
      # MinIO Client configuration
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      # Locale configuration for proper UTF-8 support
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      # Database connection configuration (for automatic database creation)
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - REDIS_PASSWORD
      # RabbitMQ Management API credentials
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    volumes:
      - ${HOST_APP_PATH}:/var/www
      - ${HOME}/.gitconfig:/home/${APP_USER}/.gitconfig:ro
      - ./workspace/auth.json:/home/${APP_USER}/.composer/auth.json
      - ./workspace/php.ini:/usr/local/etc/php/conf.d/99-dockerkit.ini:ro
      - ./workspace/entrypoint.d:/entrypoint.d:ro
      - ./workspace/crontab.d:/etc/cron.d:ro
      - ./ssl-ca:/ssl-ca:ro
      - ./dumps:/dumps:rw
      # SSH keys for deployment
      - ${HOST_SSH_PATH:-./workspace/ssh}:/ssh-keys:ro
    healthcheck:
      test: [ "CMD-SHELL", "php --version" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - web
      - backend

  ### PHP-FPM ################################################
  php-fpm:
    build:
      context: ./php-fpm
      args:
        # Core configuration
        - PHP_VERSION
        - TZ
        # User configuration
        - APP_USER
        - APP_UID
        - APP_GID
        # PHP Extensions
        - DEPENDENCY_PHP_EXTENSIONS
    restart: on-failure:3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ
      # Container user configuration
      - APP_USER
      - APP_UID
      - APP_GID
    volumes:
      - ${HOST_APP_PATH}:/var/www
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/99-dockerkit.ini:ro
      - ./php-fpm/entrypoint.d:/entrypoint.d:ro
      - ./ssl-ca:/ssl-ca:ro
    healthcheck:
      test: [ "CMD-SHELL", "php-fpm -t" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - web
      - backend

  ### NGINX ################################################
  nginx:
    image: nginx:${NGINX_VERSION}
    restart: on-failure:3
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_FPM_HOST=php-fpm
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - ${HOST_APP_PATH}:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./ssl-ca:/etc/ssl/ca:ro
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - web
      - backend

  ### PostgreSQL ###########################################
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure:3
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - TZ
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB} && psql -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1;' >/dev/null 2>&1" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
      start_period: 30s
    networks:
      - backend

  ### MySQL ################################################
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: on-failure:3
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - TZ
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost --silent && mysql -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;' >/dev/null 2>&1" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
      start_period: 30s
    networks:
      - backend

  ### MongoDB ##############################################
  mongo:
    image: mongo:${MONGODB_VERSION}
    restart: on-failure:3
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - TZ
    volumes:
      - mongo_db_data:/data/db
      - mongo_config_data:/data/configdb
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - backend

  ### Redis ################################################
  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:3
    ports:
      - "${REDIS_PORT}:6379"
    command: --requirepass ${REDIS_PASSWORD}
    environment:
      - TZ
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - backend

  ### RabbitMQ #############################################
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}-management
    restart: on-failure:3
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
      - "${RABBITMQ_WEB_STOMP_HOST_PORT}:15674"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - TZ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - backend

  ### ElasticSearch ########################################
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    restart: on-failure:3
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
    environment:
      # Single-node cluster configuration
      - cluster.name=${ELASTICSEARCH_CLUSTER_NAME:-dockerkit-cluster}
      - discovery.type=single-node
      - node.name=${ELASTICSEARCH_NODE_NAME:-dockerkit-node}

      # Memory and performance settings
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSVE=0"
      - "CLI_JAVA_OPTS=-XX:UseSVE=0"

      # Logging (reduce noise)
      - logger.level=${ELASTICSEARCH_LOG_LEVEL}
      - logger.org.elasticsearch.cluster.service=ERROR
      - logger.org.elasticsearch.discovery=ERROR

      # Caching settings
      - indices.fielddata.cache.size=${ELASTICSEARCH_CACHE_SIZE}
      - indices.queries.cache.size=10%
      - indices.requests.cache.size=5%

      # Network settings
      - http.compression=true
      - http.max_content_length=200mb
      - transport.compress=true

      # Development optimizations
      - action.auto_create_index=true
      - bootstrap.memory_lock=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.node_concurrent_recoveries=2
      - indices.recovery.max_bytes_per_sec=100mb
      - indices.id_field_data.enabled=true

      # Security settings (disabled for development)
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false

      # CORS settings for Elasticvue Web UI integration
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:${ELASTICVUE_HTTP_PORT},http://127.0.0.1:${ELASTICVUE_HTTP_PORT}
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true

      - TZ=UTC
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - web

  ### Elasticvue ###########################################
  elasticvue:
    image: cars10/elasticvue:${ELASTICVUE_VERSION}
    restart: on-failure:3
    ports:
      - "${ELASTICVUE_HTTP_PORT}:8080"
    environment:
      - TZ
      - ELASTICVUE_CLUSTERS
    volumes:
      - elasticvue_data:/usr/share/nginx/html/api
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    depends_on:
      - elasticsearch
    networks:
      - web

  ### Minio ################################################
  minio:
    image: minio/minio:${MINIO_VERSION}
    restart: on-failure:3
    command: server --console-address ":9001" /data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - TZ
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - web

  ### Mailpit ##############################################
  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION}
    restart: on-failure:3
    ports:
      - "${MAILPIT_HTTP_PORT}:8025"
      - "${MAILPIT_SMTP_PORT}:1025"
    environment:
      - TZ
    volumes:
      - mailpit_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8025 || exit 1" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    networks:
      - web

  ### Portainer ############################################
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    restart: on-failure:3
    ports:
      - "${PORTAINER_PORT}:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - management

networks:
  web:
    driver: bridge
  backend:
    driver: bridge
  management:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  mongo_db_data:
  mongo_config_data:
  redis_data:
  rabbitmq_data:
  elasticsearch_data:
  elasticvue_data:
  minio_data:
  minio_config:
  mailpit_data:
  portainer_data:
