blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/abordage/dockerkit/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/abordage/dockerkit#readme
    about: Check the documentation for setup and usage instructions
  - name: Contributing Guide
    url: https://github.com/abordage/dockerkit/blob/main/.github/CONTRIBUTING.md
    about: Learn how to contribute to DockerKit development 