#!/bin/bash

# =============================================================================
# NETWORK ALIASES GENERATOR
# =============================================================================
# Functions for generating Docker Compose network aliases for .local projects
# Usage: source this file and call alias generation functions
# =============================================================================

set -euo pipefail

# Load base functionality
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../core" && pwd)"
# shellcheck source=../core/base.sh
source "$BASE_DIR/base.sh"

# Load dependencies
ALIASES_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../core/utils.sh
source "$ALIASES_SCRIPT_DIR/../core/utils.sh"
# shellcheck source=../core/config.sh
source "$ALIASES_SCRIPT_DIR/../core/config.sh"
# shellcheck source=../core/validation.sh
source "$ALIASES_SCRIPT_DIR/../core/validation.sh"
# shellcheck source=./projects.sh
source "$ALIASES_SCRIPT_DIR/projects.sh"

# Configuration
readonly ALIASES_FILE="docker-compose.aliases.yml"

# Generate network aliases file for discovered projects
generate_network_aliases() {
    local projects=("$@")

    if [ ${#projects[@]} -eq 0 ]; then
        print_warning "No projects provided for alias generation"
        create_empty_aliases_file
        return "$EXIT_SUCCESS"
    fi

    # Create aliases file header
    create_aliases_file_header

    # Add nginx aliases (both web and backend networks)
    add_nginx_aliases "${projects[@]}"

    # Show status for each site individually
    for project in "${projects[@]}"; do
        print_success "Network alias added for: $project"
    done

    # Show final status
    print_success "Network aliases file generated: $ALIASES_FILE"

    return "$EXIT_SUCCESS"
}

# Create aliases file header
create_aliases_file_header() {
    cat > "$ALIASES_FILE" << 'EOF'
---
# =============================================================================
# AUTO-GENERATED NETWORK ALIASES
# =============================================================================
# Generated by DockerKit tools/lib/services/aliases.sh
# Do not edit manually - this file will be overwritten
#
# This file provides network aliases for .local projects, allowing containers
# to resolve project domains internally (e.g., nginx can route to workspace)
# =============================================================================

services:
EOF
}

# Add nginx service aliases
add_nginx_aliases() {
    local projects=("$@")

    cat >> "$ALIASES_FILE" << 'EOF'
  nginx:
    networks:
      web:
        aliases:
EOF

    for project in "${projects[@]}"; do
        echo "          - $project" >> "$ALIASES_FILE"
    done

    cat >> "$ALIASES_FILE" << 'EOF'
      backend:
        aliases:
EOF

    for project in "${projects[@]}"; do
        echo "          - $project" >> "$ALIASES_FILE"
    done
}

# Create empty aliases file when no projects found
create_empty_aliases_file() {
    cat > "$ALIASES_FILE" << 'EOF'
---
# =============================================================================
# AUTO-GENERATED NETWORK ALIASES
# =============================================================================
# Generated by DockerKit tools/lib/services/aliases.sh
# No .local projects found - empty configuration
# =============================================================================

services: {}
EOF

    print_info "Created empty aliases file (no projects found)"
}

# Validate aliases file exists and is readable
validate_aliases_file() {
    if [ ! -f "$ALIASES_FILE" ]; then
        print_error "Aliases file not found: $ALIASES_FILE"
        return "$EXIT_INVALID_CONFIG"
    fi

    if [ ! -r "$ALIASES_FILE" ]; then
        print_error "Aliases file not readable: $ALIASES_FILE"
        return "$EXIT_PERMISSION_DENIED"
    fi

    # Basic YAML syntax validation
    if ! docker compose version >/dev/null 2>&1; then
        print_warning "docker compose not available for validation"
        return "$EXIT_SUCCESS"
    fi

    # Test if docker compose can parse the file together with main compose file
    if ! docker compose -f docker-compose.yml -f "$ALIASES_FILE" config >/dev/null 2>&1; then
        print_error "Invalid YAML syntax in aliases file or incompatible with docker-compose.yml"
        return "$EXIT_INVALID_CONFIG"
    fi

    return "$EXIT_SUCCESS"
}

# Get aliases file path
get_aliases_file_path() {
    echo "$DOCKERKIT_DIR/$ALIASES_FILE"
}

# Remove aliases file
remove_aliases_file() {
    if [ -f "$ALIASES_FILE" ]; then
        rm -f "$ALIASES_FILE"
        print_info "Removed aliases file: $ALIASES_FILE"
    fi
}

# Show aliases file content with syntax highlighting if available
show_aliases_content() {
    if [ ! -f "$ALIASES_FILE" ]; then
        print_error "Aliases file not found: $ALIASES_FILE"
        return "$EXIT_INVALID_CONFIG"
    fi

    print_section "Generated aliases file content:"

    # Try to use syntax highlighting if available
    if command -v bat >/dev/null 2>&1; then
        bat --style=numbers --language=yaml "$ALIASES_FILE"
    elif command -v pygmentize >/dev/null 2>&1; then
        pygmentize -l yaml "$ALIASES_FILE"
    else
        # Fallback to plain cat with line numbers
        nl -ba "$ALIASES_FILE"
    fi
}

# Generate aliases from scanned projects
generate_aliases_from_scan() {
    local projects

    print_info "Scanning for .local projects..."

    if ! projects=$(scan_local_projects 2>/dev/null); then
        print_warning "No .local projects found"
        create_empty_aliases_file
        return "$EXIT_SUCCESS"
    fi

    # Convert to array
    local projects_array=()
    while IFS= read -r project; do
        projects_array+=("$project")
    done <<< "$projects"

    generate_network_aliases "${projects_array[@]}"
}

# Integration function for setup.sh
setup_network_aliases() {
    local projects=("$@")

    if [ ${#projects[@]} -eq 0 ]; then
        print_info "No projects provided, scanning automatically..."
        generate_aliases_from_scan
    else
        generate_network_aliases "${projects[@]}"
    fi

    # Validate generated file
    if ! validate_aliases_file; then
        print_error "Failed to validate generated aliases file"
        return "$EXIT_INVALID_CONFIG"
    fi

    return "$EXIT_SUCCESS"
}
