#!/bin/bash

# =============================================================================
# DEBEZIUM INSTANCES GENERATOR
# =============================================================================
# Generates docker-compose.debezium.yml from debezium/instances/*/
# Usage: source this file and call debezium management functions
# =============================================================================

set -euo pipefail

# Load base functionality
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../core" && pwd)"

# shellcheck source=tools/lib/core/base.sh
source "$BASE_DIR/base.sh"

# Load dependencies
DEBEZIUM_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tools/lib/core/utils.sh
source "$DEBEZIUM_SCRIPT_DIR/../core/utils.sh"
# shellcheck source=tools/lib/core/config.sh
source "$DEBEZIUM_SCRIPT_DIR/../core/config.sh"

readonly DEBEZIUM_COMPOSE_FILE="docker-compose.debezium.yml"
readonly DEBEZIUM_INSTANCES_DIR="debezium/instances"
readonly DEBEZIUM_TEMPLATE_DIR="$DEBEZIUM_INSTANCES_DIR/_template"
readonly DEBEZIUM_DEFAULT_VERSION="3.0.8.Final"

debezium_instances_enabled() {
    local instances
    instances=$(discover_debezium_instances)
    [ -n "$instances" ] && return 0

    if [ -f "$DOCKERKIT_DIR/.env" ] && grep -qE '(^|[[:space:]])debezium-' <<< "$(grep '^ENABLE_SERVICES=' "$DOCKERKIT_DIR/.env" 2>/dev/null || true)"; then
        return 0
    fi

    return 1
}

ensure_debezium_env_variables() {
    local env_file="$DOCKERKIT_DIR/.env"

    if [ ! -f "$env_file" ]; then
        return 0
    fi

    if ! debezium_instances_enabled; then
        return 0
    fi

    if grep -q '^DEBEZIUM_VERSION=' "$env_file"; then
        return 0
    fi

    print_info "Adding missing Debezium variables to .env"

    cat >> "$env_file" << 'EOF'

# =============================================================================
# Debezium Configuration (PostgreSQL CDC to RabbitMQ)
# =============================================================================
# Added automatically — see .env.example for documentation
DEBEZIUM_VERSION=3.0.8.Final
DEBEZIUM_SERVER_PORT_BASE=8081
DEBEZIUM_DB_USER=debezium
DEBEZIUM_DB_PASSWORD="${DEFAULT_PASSWORD}"
DEBEZIUM_RABBITMQ_EXCHANGE=cdc
EOF

    print_success "Debezium variables added to .env"
    return 0
}

generate_debezium_yaml_header() {
    cat << 'EOF'
---
# =============================================================================
# AUTO-GENERATED DEBEZIUM INSTANCES
# =============================================================================
# Generated by DockerKit tools/lib/services/debezium.sh
# Do not edit manually - this file will be overwritten
#
# Add instances: make debezium-instance INSTANCE=name DATABASE=db_name
# Enable in .env: ENABLE_SERVICES="... debezium-<instance> ..."
# =============================================================================

EOF
}

validate_instance_name() {
    local name="$1"

    if [[ ! "$name" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
        print_error "Invalid instance name '$name'. Use letters, numbers, underscore, or hyphen."
        return "$EXIT_INVALID_INPUT"
    fi

    if [[ "$name" == "_template" ]]; then
        print_error "Reserved instance name: _template"
        return "$EXIT_INVALID_INPUT"
    fi

    return "$EXIT_SUCCESS"
}

sanitize_volume_suffix() {
    local name="$1"
    echo "${name//-/_}"
}

discover_debezium_instances() {
    local instances_dir="$DOCKERKIT_DIR/$DEBEZIUM_INSTANCES_DIR"
    local instance

    if [ ! -d "$instances_dir" ]; then
        return "$EXIT_SUCCESS"
    fi

    for instance in "$instances_dir"/*; do
        [ -d "$instance" ] || continue
        instance="$(basename "$instance")"
        [ "$instance" = "_template" ] && continue
        [ -f "$instances_dir/$instance/application.properties" ] || continue
        echo "$instance"
    done
}

read_instance_server_port() {
    local instance_dir="$1"
    local default_port="$2"
    local port="$default_port"

    if [ -f "$instance_dir/instance.env" ]; then
        # shellcheck disable=SC1090
        source "$instance_dir/instance.env"
        port="${SERVER_PORT:-$default_port}"
    fi

    echo "$port"
}

create_empty_debezium_compose() {
    generate_debezium_yaml_header > "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE"
    cat >> "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE" << 'EOF'
services: {}

volumes: {}
EOF
}

append_debezium_service() {
    local instance="$1"
    local server_port="$2"
    local service_name="debezium-${instance}"
    local volume_name="debezium_$(sanitize_volume_suffix "$instance")_data"

    cat >> "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE" << EOF
  ${service_name}:
    image: quay.io/debezium/server:\${DEBEZIUM_VERSION:-${DEBEZIUM_DEFAULT_VERSION}}
    restart: unless-stopped
    ports:
      - "${server_port}:8080"
    environment:
      - TZ
      - DEBEZIUM_SOURCE_DATABASE_HOSTNAME=postgres
      - DEBEZIUM_SOURCE_DATABASE_PORT=5432
      - DEBEZIUM_SOURCE_DATABASE_USER=\${DEBEZIUM_DB_USER:-debezium}
      - DEBEZIUM_SOURCE_DATABASE_PASSWORD=\${DEBEZIUM_DB_PASSWORD:-\${DEFAULT_PASSWORD}}
      - DEBEZIUM_SINK_RABBITMQ_CONNECTION_HOST=rabbitmq
      - DEBEZIUM_SINK_RABBITMQ_CONNECTION_PORT=5672
      - DEBEZIUM_SINK_RABBITMQ_CONNECTION_USERNAME=\${RABBITMQ_DEFAULT_USER}
      - DEBEZIUM_SINK_RABBITMQ_CONNECTION_PASSWORD=\${RABBITMQ_DEFAULT_PASS}
      - DEBEZIUM_SINK_RABBITMQ_EXCHANGE=\${DEBEZIUM_RABBITMQ_EXCHANGE:-cdc}
    volumes:
      - ./debezium/instances/${instance}/application.properties:/debezium/config/application.properties:ro
      - ${volume_name}:/debezium/data
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/q/health || exit 1" ]
      interval: \${HEALTH_CHECK_INTERVAL}
      timeout: \${HEALTH_CHECK_TIMEOUT}
      retries: \${HEALTH_CHECK_RETRIES}
      start_period: 60s
    networks:
      - backend

EOF
}

append_debezium_volume() {
    local instance="$1"
    local volume_name="debezium_$(sanitize_volume_suffix "$instance")_data"

    echo "  ${volume_name}:" >> "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE"
}

generate_debezium_compose() {
    local instances=()
    local instance
    local base_port="${DEBEZIUM_SERVER_PORT_BASE:-8080}"
    local port_index=0
    local server_port

    while IFS= read -r instance; do
        [ -n "$instance" ] && instances+=("$instance")
    done < <(discover_debezium_instances)

    if [ ${#instances[@]} -eq 0 ]; then
        create_empty_debezium_compose
        print_info "No Debezium instances found (create with: make debezium-instance)"
        return "$EXIT_SUCCESS"
    fi

    generate_debezium_yaml_header > "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE"
    echo "services:" >> "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE"

    for instance in "${instances[@]}"; do
        server_port=$(read_instance_server_port \
            "$DOCKERKIT_DIR/$DEBEZIUM_INSTANCES_DIR/$instance" \
            "$((base_port + port_index))")
        append_debezium_service "$instance" "$server_port"
        print_success "Debezium instance configured: debezium-${instance} (port ${server_port})"
        port_index=$((port_index + 1))
    done

    echo "" >> "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE"
    echo "volumes:" >> "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE"

    for instance in "${instances[@]}"; do
        append_debezium_volume "$instance"
    done

    print_success "Debezium compose file generated: $DEBEZIUM_COMPOSE_FILE"
    return "$EXIT_SUCCESS"
}

validate_debezium_compose() {
    local compose_files="-f docker-compose.yml"

    if [ ! -f "$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE" ]; then
        print_error "Debezium compose file not found: $DEBEZIUM_COMPOSE_FILE"
        return "$EXIT_INVALID_CONFIG"
    fi

    if ! docker compose version >/dev/null 2>&1; then
        print_warning "docker compose not available for Debezium validation"
        return "$EXIT_SUCCESS"
    fi

    if [ -f "$DOCKERKIT_DIR/docker-compose.aliases.yml" ]; then
        compose_files="$compose_files -f docker-compose.aliases.yml"
    fi
    compose_files="$compose_files -f $DEBEZIUM_COMPOSE_FILE"

    if ! (cd "$DOCKERKIT_DIR" && docker compose $compose_files config >/dev/null 2>&1); then
        print_error "Invalid Debezium compose file or incompatible with docker-compose.yml"
        return "$EXIT_INVALID_CONFIG"
    fi

    return "$EXIT_SUCCESS"
}

setup_debezium_compose() {
    ensure_debezium_env_variables

    if [ -f "$DOCKERKIT_DIR/.env" ]; then
        # shellcheck disable=SC1091
        set -a && source "$DOCKERKIT_DIR/.env" && set +a
    fi

    generate_debezium_compose || return "$?"

    if ! validate_debezium_compose; then
        return "$EXIT_INVALID_CONFIG"
    fi

    return "$EXIT_SUCCESS"
}

replace_template_placeholders() {
    local file="$1"
    local instance="$2"
    local database="$3"
    local temp_file="${file}.tmp"

    sed \
        -e "s/__INSTANCE__/${instance}/g" \
        -e "s/__DATABASE__/${database}/g" \
        "$file" > "$temp_file"
    mv "$temp_file" "$file"
}

create_debezium_instance() {
    local instance="$1"
    local database="$2"
    local server_port="${3:-}"
    local instance_dir="$DOCKERKIT_DIR/$DEBEZIUM_INSTANCES_DIR/$instance"
    local next_port

    if ! validate_instance_name "$instance"; then
        return "$EXIT_INVALID_INPUT"
    fi

    if [ -z "$database" ]; then
        print_error "DATABASE is required"
        return "$EXIT_INVALID_INPUT"
    fi

    if [ -d "$instance_dir" ]; then
        print_error "Instance already exists: $instance"
        return "$EXIT_INVALID_INPUT"
    fi

    if [ ! -f "$DOCKERKIT_DIR/$DEBEZIUM_TEMPLATE_DIR/application.properties.example" ]; then
        print_error "Template not found: $DEBEZIUM_TEMPLATE_DIR/application.properties.example"
        return "$EXIT_INVALID_CONFIG"
    fi

    if [ -f "$DOCKERKIT_DIR/.env" ]; then
        # shellcheck disable=SC1091
        set -a && source "$DOCKERKIT_DIR/.env" && set +a
    fi

    mkdir -p "$instance_dir"

    cp "$DOCKERKIT_DIR/$DEBEZIUM_TEMPLATE_DIR/application.properties.example" \
        "$instance_dir/application.properties"
    replace_template_placeholders "$instance_dir/application.properties" "$instance" "$database"

    if [ -n "$server_port" ]; then
        echo "SERVER_PORT=${server_port}" > "$instance_dir/instance.env"
    else
        local existing_count
        existing_count=$(discover_debezium_instances | wc -l | tr -d ' ')
        next_port=$((DEBEZIUM_SERVER_PORT_BASE + existing_count))
        echo "SERVER_PORT=${next_port}" > "$instance_dir/instance.env"
    fi

    print_success "Created Debezium instance: $instance (database: $database)"
    print_tip "Edit debezium/instances/${instance}/application.properties (table.include.list)"
    print_tip "Enable with: debezium-${instance} in ENABLE_SERVICES"
    print_tip "Run: make setup (or regenerate compose) to apply docker-compose.debezium.yml"

    setup_debezium_compose || return "$?"

    return "$EXIT_SUCCESS"
}

remove_debezium_compose() {
    local compose_file="$DOCKERKIT_DIR/$DEBEZIUM_COMPOSE_FILE"

    if [ -f "$compose_file" ]; then
        rm -f "$compose_file"
        print_success "Removed Debezium compose file"
    fi
}
