name: Links Check

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 2:00 AM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  links-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Links Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.6.1
        with:
          args: --cache --max-cache-age 1d --exclude-mail './**/*.md'
          fail: false
          jobSummary: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
