name: Markdown Lint

on:
  push:
    paths:
      - '**.md'
      - '**.markdown'
  pull_request:
    paths:
      - '**.md'
      - '**.markdown'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Lint Markdown files

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
          separator: '\n'
